language: python
python:
- '2.6'
- '2.7'
- '3.3'
- '3.4'
- pypy
install:
- pip install .
- pip install -r requirements.txt
script: python -m unittest
before_install:
- openssl aes-256-cbc -K $encrypted_1480096738d9_key -iv $encrypted_1480096738d9_iv
  -in secret.py.enc -out secret.py -d
